package everything.gui;

import everything.calc.Calc;
import everything.data.PyTripListModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author iris06
 */
public class PyTripGui extends javax.swing.JFrame
{

  /**
   * Creates new form PyTripGui
   */
  public PyTripGui()
  {
    initComponents();
    setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  
  @SuppressWarnings("unchecked")
  
  private class PyTripWorker extends SwingWorker<Calc, Object>
  {
    private final int obergrenze;

    public PyTripWorker(int obergrenze)
    {
      this.obergrenze = obergrenze;
    }

    @Override
    protected Calc doInBackground() throws Exception
    {
     return new Calc(obergrenze);
    }

    @Override
    protected void done()
    {
      
    }
    
  }
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    java.awt.GridBagConstraints gridBagConstraints;

    pMain = new javax.swing.JPanel();
    progressbar = new javax.swing.JProgressBar();
    pWest = new javax.swing.JPanel();
    pBefehle = new javax.swing.JPanel();
    pButtons = new javax.swing.JPanel();
    btBerechnen = new javax.swing.JButton();
    btBeenden = new javax.swing.JButton();
    btLoeschen = new javax.swing.JButton();
    pEingabe = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    tfErgebnisse = new javax.swing.JFormattedTextField();
    tfDauer = new javax.swing.JFormattedTextField();
    spObergrenze = new javax.swing.JSpinner();
    jLabel4 = new javax.swing.JLabel();
    pOst = new javax.swing.JPanel();
    ScrollPane = new javax.swing.JScrollPane();
    listenfeld = new javax.swing.JList<>();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Wiederholungsübung");
    addWindowListener(new java.awt.event.WindowAdapter()
    {
      public void windowClosing(java.awt.event.WindowEvent evt)
      {
        onWindowClosing(evt);
      }
    });

    pMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
    pMain.setLayout(new java.awt.BorderLayout());
    pMain.add(progressbar, java.awt.BorderLayout.SOUTH);

    pWest.setLayout(new java.awt.BorderLayout());

    pBefehle.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8), javax.swing.BorderFactory.createTitledBorder("Befehle")));

    pButtons.setLayout(new java.awt.GridLayout(0, 1));

    btBerechnen.setBackground(new java.awt.Color(255, 204, 204));
    btBerechnen.setForeground(new java.awt.Color(0, 0, 0));
    btBerechnen.setText("Berechnen");
    btBerechnen.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onBerechnen(evt);
      }
    });
    pButtons.add(btBerechnen);

    btBeenden.setBackground(new java.awt.Color(255, 204, 204));
    btBeenden.setForeground(new java.awt.Color(0, 0, 0));
    btBeenden.setText("Beenden");
    btBeenden.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onBeenden(evt);
      }
    });
    pButtons.add(btBeenden);

    btLoeschen.setBackground(new java.awt.Color(255, 204, 204));
    btLoeschen.setForeground(new java.awt.Color(0, 0, 0));
    btLoeschen.setText("Löschen");
    btLoeschen.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onLoeschen(evt);
      }
    });
    pButtons.add(btLoeschen);

    pBefehle.add(pButtons);

    pWest.add(pBefehle, java.awt.BorderLayout.PAGE_END);

    pEingabe.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8), javax.swing.BorderFactory.createTitledBorder("Eingabe")));
    java.awt.GridBagLayout pEingabeLayout = new java.awt.GridBagLayout();
    pEingabeLayout.columnWidths = new int[] {0, 8, 0, 8, 0, 8, 0, 8, 0};
    pEingabeLayout.rowHeights = new int[] {0, 8, 0, 8, 0};
    pEingabe.setLayout(pEingabeLayout);

    jLabel1.setText("Obergrenze");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    pEingabe.add(jLabel1, gridBagConstraints);

    jLabel2.setText("Ergebnisse");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    pEingabe.add(jLabel2, gridBagConstraints);

    jLabel3.setText("Dauer");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    pEingabe.add(jLabel3, gridBagConstraints);

    tfErgebnisse.setEditable(false);
    tfErgebnisse.setColumns(10);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 2;
    pEingabe.add(tfErgebnisse, gridBagConstraints);

    tfDauer.setColumns(10);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 4;
    pEingabe.add(tfDauer, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
    pEingabe.add(spObergrenze, gridBagConstraints);

    jLabel4.setText("ms");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 4;
    pEingabe.add(jLabel4, gridBagConstraints);

    pWest.add(pEingabe, java.awt.BorderLayout.PAGE_START);

    pMain.add(pWest, java.awt.BorderLayout.LINE_START);

    pOst.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8), javax.swing.BorderFactory.createTitledBorder("Liste")));
    pOst.setLayout(new java.awt.BorderLayout());

    ScrollPane.setViewportView(listenfeld);

    pOst.add(ScrollPane, java.awt.BorderLayout.CENTER);

    pMain.add(pOst, java.awt.BorderLayout.LINE_END);

    getContentPane().add(pMain, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void onBerechnen(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onBerechnen
  {//GEN-HEADEREND:event_onBerechnen
    try
    {
      btBerechnen.setEnabled(false);
      progressbar.setIndeterminate(true);
      progressbar.setString("Load ...");
      progressbar.setStringPainted(true);
      loeschen();
    
    final int obergrenze = ((Number)spObergrenze.getValue()).intValue();
    new PyTripWorker(obergrenze).execute();
    }
    catch (Exception ex)
    {
      JOptionPane.showMessageDialog(this, ex.getMessage(),
        "Fehler aufgetreten", JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_onBerechnen

  private void loeschen()
  {
    tfDauer.setValue(0);
    tfErgebnisse.setValue(0);
    listenfeld.setModel(new PyTripListModel (new ArrayList<>()));
  }
  
  private void onBeenden(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onBeenden
  {//GEN-HEADEREND:event_onBeenden
    onX();
  }//GEN-LAST:event_onBeenden

  private void onLoeschen(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onLoeschen
  {//GEN-HEADEREND:event_onLoeschen
    loeschen();
  }//GEN-LAST:event_onLoeschen

  private void onWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_onWindowClosing
  {//GEN-HEADEREND:event_onWindowClosing
    onX();
  }//GEN-LAST:event_onWindowClosing

  private void onX()
  {
    if (JOptionPane.showConfirmDialog(this, "Wirklich beenden?", 
      "Sicherheitsabfrage", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
      dispose();
  }
  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(PyTripGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(PyTripGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(PyTripGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(PyTripGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new PyTripGui().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane ScrollPane;
  private javax.swing.JButton btBeenden;
  private javax.swing.JButton btBerechnen;
  private javax.swing.JButton btLoeschen;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JList<everything.data.PyTrip> listenfeld;
  private javax.swing.JPanel pBefehle;
  private javax.swing.JPanel pButtons;
  private javax.swing.JPanel pEingabe;
  private javax.swing.JPanel pMain;
  private javax.swing.JPanel pOst;
  private javax.swing.JPanel pWest;
  private javax.swing.JProgressBar progressbar;
  private javax.swing.JSpinner spObergrenze;
  private javax.swing.JFormattedTextField tfDauer;
  private javax.swing.JFormattedTextField tfErgebnisse;
  // End of variables declaration//GEN-END:variables
}
