/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ue07.gui;

import ue07.gui.DoubleListModel;
import java.util.*;
import javax.swing.JOptionPane;
import ue07.calc.StatisticRechner;

/**
 *
 * @author iris06
 */
public class StatisticGui extends javax.swing.JFrame
{
  private final List<Double> zahlen = new ArrayList<>();

  /**
   * Creates new form StatisticGui
   */
  public StatisticGui()
  {
    initComponents();
    //zahlen.add(3.14);
    //zahlen.add(-123.45);
    updateModel();
    
  }

   private void updateModel()
   {
     listenfeld.setModel(new DoubleListModel(zahlen));
   }
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    java.awt.GridBagConstraints gridBagConstraints;

    pMain = new javax.swing.JPanel();
    pSouth = new javax.swing.JPanel();
    pButtons = new javax.swing.JPanel();
    btHinzu = new javax.swing.JButton();
    btBerechnen = new javax.swing.JButton();
    btAlleLoeschen = new javax.swing.JButton();
    btLoeschen = new javax.swing.JButton();
    btBeenden = new javax.swing.JButton();
    pList = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    listenfeld = new javax.swing.JList<>();
    pEast = new javax.swing.JPanel();
    pAusgabe = new javax.swing.JPanel();
    ftfStandard = new javax.swing.JFormattedTextField();
    ftfDurchschnitt = new javax.swing.JFormattedTextField();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    pEingabe = new javax.swing.JPanel();
    ftfZahl = new javax.swing.JFormattedTextField();
    jLabel3 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Statistische Berechnung");
    setLocationByPlatform(true);

    pMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
    pMain.setLayout(new java.awt.BorderLayout(0, 8));

    pSouth.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

    pButtons.setLayout(new java.awt.GridLayout(1, 0));

    btHinzu.setText("Hinzufügen");
    btHinzu.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        OnHinzufuegen(evt);
      }
    });
    pButtons.add(btHinzu);

    btBerechnen.setText("Berechnen");
    btBerechnen.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onBerechnen(evt);
      }
    });
    pButtons.add(btBerechnen);

    btAlleLoeschen.setText("Alle Löschen");
    btAlleLoeschen.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onAlleLoeschen(evt);
      }
    });
    pButtons.add(btAlleLoeschen);

    btLoeschen.setText("Löschen");
    btLoeschen.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onLoeschen(evt);
      }
    });
    pButtons.add(btLoeschen);

    btBeenden.setText("Beenden");
    btBeenden.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onBeenden(evt);
      }
    });
    pButtons.add(btBeenden);

    pSouth.add(pButtons);

    pMain.add(pSouth, java.awt.BorderLayout.SOUTH);

    pList.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Liste der Zahlen"), javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8)));
    pList.setLayout(new java.awt.BorderLayout());

    jScrollPane1.setViewportView(listenfeld);

    pList.add(jScrollPane1, java.awt.BorderLayout.CENTER);

    pMain.add(pList, java.awt.BorderLayout.CENTER);

    pEast.setLayout(new java.awt.BorderLayout());

    pAusgabe.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Ausgabe"), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
    java.awt.GridBagLayout pAusgabeLayout = new java.awt.GridBagLayout();
    pAusgabeLayout.columnWidths = new int[] {0, 8, 0};
    pAusgabeLayout.rowHeights = new int[] {0, 8, 0};
    pAusgabe.setLayout(pAusgabeLayout);

    ftfStandard.setColumns(10);
    ftfStandard.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
    ftfStandard.setValue(0.0);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 0;
    pAusgabe.add(ftfStandard, gridBagConstraints);

    ftfDurchschnitt.setColumns(10);
    ftfDurchschnitt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
    ftfDurchschnitt.setValue(0.0);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 2;
    pAusgabe.add(ftfDurchschnitt, gridBagConstraints);

    jLabel1.setText("Durchschnitt");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
    pAusgabe.add(jLabel1, gridBagConstraints);

    jLabel2.setText("Standardabweichung");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
    pAusgabe.add(jLabel2, gridBagConstraints);

    pEast.add(pAusgabe, java.awt.BorderLayout.PAGE_END);

    pEingabe.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Eingabe"), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
    pEingabe.setLayout(new java.awt.BorderLayout());

    ftfZahl.setColumns(10);
    ftfZahl.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
    ftfZahl.setValue(0.0);
    pEingabe.add(ftfZahl, java.awt.BorderLayout.CENTER);

    jLabel3.setText("Zahl");
    pEingabe.add(jLabel3, java.awt.BorderLayout.WEST);

    pEast.add(pEingabe, java.awt.BorderLayout.PAGE_START);

    pMain.add(pEast, java.awt.BorderLayout.EAST);

    getContentPane().add(pMain, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void OnHinzufuegen(java.awt.event.ActionEvent evt)//GEN-FIRST:event_OnHinzufuegen
  {//GEN-HEADEREND:event_OnHinzufuegen
    final double zahl =
    ((Number)ftfZahl.getValue()).doubleValue();
    zahlen.add(zahl);
    listenfeld.setModel(new DoubleListModel(zahlen));
    updateModel();
  }//GEN-LAST:event_OnHinzufuegen

  private void onBerechnen(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onBerechnen
  {//GEN-HEADEREND:event_onBerechnen
    try
    {
     final StatisticRechner rechner = new StatisticRechner(zahlen);
     final double
       durchschnitt = rechner.getDurchschnitt(),
       stdAbw = rechner.getStdAbw(); //Ergebnisse abholen
       ftfDurchschnitt.setValue(durchschnitt); //Ergebnisse ausgeben
       ftfStandard.setValue(stdAbw);
       
    }
    catch (Exception ex)
    {
      JOptionPane.showMessageDialog(this, ex.getMessage(),
        "Fehler aufgetreten", JOptionPane.ERROR_MESSAGE);
    }
    updateModel();
  }//GEN-LAST:event_onBerechnen

  private void onLoeschen(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onLoeschen
  {//GEN-HEADEREND:event_onLoeschen
    //Version 1: Ein selektierten Eintrag löschen:
    /*final int selIndex = listenfeld.getSelectedIndex(); //1. Index holen des selektierten Eintrags
    if (selIndex < 0) //Kein Eintrag selektiert
      JOptionPane.showMessageDialog(this,"Bitte erst einen Eintrag selektieren", 
        "Fehler aufgetretern", JOptionPane.ERROR_MESSAGE);
    else
      if (JOptionPane.showConfirmDialog(
    this, "Eintrag wirklich löschen?", "Sicherheitsabfrage",
      JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
        
      {
        zahlen.remove(selIndex);
        listenfeld.setModel(new DoubleListModel(zahlen));
      }*/
    final int[] sel = listenfeld.getSelectedIndices(); //Indices der selektierten Einträge
    if (sel.length==0)//Kein Eintrag selektiert
      JOptionPane.showMessageDialog(this,"Bitte mindestens einen Eintrag selektieren", 
        "Fehler aufgetreten", JOptionPane.ERROR_MESSAGE);
    else
      if (JOptionPane.showConfirmDialog(
    this, 
        sel.length==1
        ? "Selektierte Einträge wirklich löschen?" 
        : String.format(" %d Einträge wirklich löschen?", sel.length), "Sicherheitsabfrage",
      JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION);
    {
      for (int i = sel.length-1; i>=0; i--) //Alle selektierten EInträge in der Kollektion gelöscht
        zahlen.remove(sel[i]);
    }
    
    updateModel();
  }//GEN-LAST:event_onLoeschen

  private void onBeenden(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onBeenden
  {//GEN-HEADEREND:event_onBeenden
    onX();
  }//GEN-LAST:event_onBeenden

  private void onAlleLoeschen(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onAlleLoeschen
  {//GEN-HEADEREND:event_onAlleLoeschen
   final int[] sel = listenfeld.getSelectedIndices(); //Indices der selektierten Einträge
   zahlen.clear();
   if(zahlen.size() >0);
   updateModel();
   
  }//GEN-LAST:event_onAlleLoeschen
  private void onX()
  {
     if (JOptionPane.showConfirmDialog(
    this, "Wirklich beenden?", "Sicherheitsabfrage",
      JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
       dispose();
  }
    
  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(StatisticGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(StatisticGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(StatisticGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(StatisticGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new StatisticGui().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btAlleLoeschen;
  private javax.swing.JButton btBeenden;
  private javax.swing.JButton btBerechnen;
  private javax.swing.JButton btHinzu;
  private javax.swing.JButton btLoeschen;
  private javax.swing.JFormattedTextField ftfDurchschnitt;
  private javax.swing.JFormattedTextField ftfStandard;
  private javax.swing.JFormattedTextField ftfZahl;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JList<Double> listenfeld;
  private javax.swing.JPanel pAusgabe;
  private javax.swing.JPanel pButtons;
  private javax.swing.JPanel pEast;
  private javax.swing.JPanel pEingabe;
  private javax.swing.JPanel pList;
  private javax.swing.JPanel pMain;
  private javax.swing.JPanel pSouth;
  // End of variables declaration//GEN-END:variables
}
