/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ue05;

import javax.swing.JOptionPane;
import ue01.SpritRechner;

/**
 *
 * @author iris06
 */
public class BetterSpritGUI extends javax.swing.JFrame
{

  /**
   * Creates new form BetterSpritGUI
   */
  public BetterSpritGUI()
  {
    initComponents();
    setLocationRelativeTo(null);
  }
  

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    java.awt.GridBagConstraints gridBagConstraints;

    jScrollPane1 = new javax.swing.JScrollPane();
    pMain = new javax.swing.JPanel();
    pButton = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();
    btBeenden = new javax.swing.JButton();
    btBerechnen = new javax.swing.JButton();
    pContent = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    tfDistanz = new javax.swing.JFormattedTextField();
    tfVerbrauch = new javax.swing.JFormattedTextField();
    tfDurchschnitt = new javax.swing.JFormattedTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    setTitle("Spritberechnung V0.2");
    setLocationByPlatform(true);
    addWindowListener(new java.awt.event.WindowAdapter()
    {
      public void windowClosing(java.awt.event.WindowEvent evt)
      {
        onWindowClosing(evt);
      }
    });

    pMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
    pMain.setLayout(new java.awt.BorderLayout(0, 8));

    jPanel1.setLayout(new java.awt.GridLayout(1, 2, 8, 0));

    btBeenden.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    btBeenden.setText("Programm beenden");
    btBeenden.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onBeenden(evt);
      }
    });
    jPanel1.add(btBeenden);

    btBerechnen.setBackground(new java.awt.Color(0, 102, 102));
    btBerechnen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    btBerechnen.setText("Berechnen");
    btBerechnen.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onBerechnen(evt);
      }
    });
    jPanel1.add(btBerechnen);

    pButton.add(jPanel1);

    pMain.add(pButton, java.awt.BorderLayout.PAGE_END);

    java.awt.GridBagLayout pContentLayout = new java.awt.GridBagLayout();
    pContentLayout.columnWidths = new int[] {0, 8, 0, 8, 0};
    pContentLayout.rowHeights = new int[] {0, 8, 0, 8, 0};
    pContent.setLayout(pContentLayout);

    jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel1.setText("Distanz");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    pContent.add(jLabel1, gridBagConstraints);

    jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel2.setText("Verbrauch");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    pContent.add(jLabel2, gridBagConstraints);

    jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel3.setText("Durchschnittsverbrauch");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    pContent.add(jLabel3, gridBagConstraints);

    jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel4.setText("km");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    pContent.add(jLabel4, gridBagConstraints);

    jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel5.setText("liter");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    pContent.add(jLabel5, gridBagConstraints);

    jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel6.setText("l/100km");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    pContent.add(jLabel6, gridBagConstraints);

    tfDistanz.setColumns(10);
    tfDistanz.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0.00"))));
    tfDistanz.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    tfDistanz.setValue(0.0);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 0;
    pContent.add(tfDistanz, gridBagConstraints);

    tfVerbrauch.setColumns(10);
    tfVerbrauch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    tfVerbrauch.setValue(0.0);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 2;
    pContent.add(tfVerbrauch, gridBagConstraints);

    tfDurchschnitt.setEditable(false);
    tfDurchschnitt.setColumns(10);
    tfDurchschnitt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    tfDurchschnitt.setValue(0.0);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 4;
    pContent.add(tfDurchschnitt, gridBagConstraints);

    pMain.add(pContent, java.awt.BorderLayout.CENTER);

    jScrollPane1.setViewportView(pMain);

    getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void onBerechnen(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onBerechnen
  {//GEN-HEADEREND:event_onBerechnen
    try
    {
      //Werte holen
      final double distanz =((Number)tfDistanz.getValue()).doubleValue(),
        verbrauch = ((Number)tfVerbrauch.getValue()).doubleValue();
      
      final SpritRechner rechner = new SpritRechner (distanz, verbrauch);
      tfDurchschnitt.setValue(rechner.getDurchschnittsverbrauch());

    }
    catch (Exception e)
    {
      JOptionPane.showMessageDialog(this, e.getMessage(),
        "Fehler aufgetreten", JOptionPane.ERROR_MESSAGE);
      
    }
    
  }//GEN-LAST:event_onBerechnen
  private void onX()
  {
    if (JOptionPane.showConfirmDialog(
    this, "Wirklich beenden?", "Sicherheitsabfrage",
      JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
      dispose();
  }
  private void onBeenden(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onBeenden
  {//GEN-HEADEREND:event_onBeenden
    onX();
  }//GEN-LAST:event_onBeenden

  private void onWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_onWindowClosing
  {//GEN-HEADEREND:event_onWindowClosing
    onX();
  }//GEN-LAST:event_onWindowClosing

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(BetterSpritGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(BetterSpritGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(BetterSpritGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(BetterSpritGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new BetterSpritGUI().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btBeenden;
  private javax.swing.JButton btBerechnen;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JPanel pButton;
  private javax.swing.JPanel pContent;
  private javax.swing.JPanel pMain;
  private javax.swing.JFormattedTextField tfDistanz;
  private javax.swing.JFormattedTextField tfDurchschnitt;
  private javax.swing.JFormattedTextField tfVerbrauch;
  // End of variables declaration//GEN-END:variables

  
}
