/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ue05;

import java.util.NoSuchElementException;
import java.util.Scanner;
import javax.swing.JOptionPane;
import ue01.SpritRechner;

/**
 *
 * @author iris06
 */
public class SpritGUI extends javax.swing.JFrame
{

  /**
   * Creates new form SpritGUI
   */
  public SpritGUI()
  {
    initComponents();
    setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jScrollPane1 = new javax.swing.JScrollPane();
    pMain = new javax.swing.JPanel();
    btBerechnen = new javax.swing.JButton();
    pContent = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    tfKm = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    tfLiter = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    tfDurchschnitt = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Spritverbrauch V 0.1");
    setLocation(new java.awt.Point(0, 0));
    setLocationByPlatform(true);

    pMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
    pMain.setLayout(new java.awt.BorderLayout(0, 8));

    btBerechnen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    btBerechnen.setText("Berechnen");
    btBerechnen.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onBerechnen(evt);
      }
    });
    pMain.add(btBerechnen, java.awt.BorderLayout.PAGE_END);

    pContent.setLayout(new java.awt.GridLayout(0, 2, 4, 8));

    jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel1.setText("Gefahrene km");
    pContent.add(jLabel1);

    tfKm.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    pContent.add(tfKm);

    jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel2.setText("Verbrauch in Liter");
    pContent.add(jLabel2);

    tfLiter.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    pContent.add(tfLiter);

    jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel3.setText("Durchschnittverbrauch");
    pContent.add(jLabel3);

    tfDurchschnitt.setEditable(false);
    tfDurchschnitt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    tfDurchschnitt.setFocusable(false);
    pContent.add(tfDurchschnitt);

    pMain.add(pContent, java.awt.BorderLayout.CENTER);

    jScrollPane1.setViewportView(pMain);

    getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void onBerechnen(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onBerechnen
  {//GEN-HEADEREND:event_onBerechnen
    try
    {
      //km umwandeln
      //final String sKm = tfKm.getText(); //Text aus Eingabefeld auslesen
      //Scanner scanner = new Scanner(sKm); //Scanner Objekt zum Umwandeln erzeugen
      //final double km = scanner.nextDouble(); //Umwandeln
       
      final double km =  new Scanner(tfKm.getText()).nextDouble();
      //Liter umwandeln als Einzeiler
      final double liter = new Scanner(tfLiter.getText()).nextDouble();

      //Rechnen
      final SpritRechner rechner = new SpritRechner(km, liter);
      final double durchschnitt = rechner.getDurchschnittsverbrauch();

      //Ausgabe
      final String sDurchschnitt = String.format("%.2f", durchschnitt);
      tfDurchschnitt.setText(sDurchschnitt);
    }
    catch (NoSuchElementException e)
    {
      JOptionPane.showMessageDialog(this, "Ungültiges Eingabeformat!",
        "Fehler aufgetreten!", JOptionPane.ERROR_MESSAGE);
    }
    catch (Exception e)
    {
      JOptionPane.showMessageDialog(this, e.getMessage(),
        "Fehler aufgetreten!", JOptionPane.ERROR_MESSAGE);
      e.printStackTrace();
    }

    
  }//GEN-LAST:event_onBerechnen

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(SpritGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(SpritGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(SpritGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(SpritGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new SpritGUI().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btBerechnen;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JPanel pContent;
  private javax.swing.JPanel pMain;
  private javax.swing.JTextField tfDurchschnitt;
  private javax.swing.JTextField tfKm;
  private javax.swing.JTextField tfLiter;
  // End of variables declaration//GEN-END:variables
}
