/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ue04;

/**
 *
 * @author iris06
 */
public class MeinErstesJavaSwingFenster extends javax.swing.JFrame
{
  private int zaehler = 0;

  /**
   * Creates new form MeinErstesJavaSwingFenster
   */
  public MeinErstesJavaSwingFenster()
  {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    lbText = new javax.swing.JLabel();
    tfText = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Titelchen");

    lbText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    lbText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lbText.setText("Anzahl: ");
    getContentPane().add(lbText, java.awt.BorderLayout.CENTER);

    tfText.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
    getContentPane().add(tfText, java.awt.BorderLayout.PAGE_START);

    jButton1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
    jButton1.setText("DRÜCK MICH");
    jButton1.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onDrueckMich(evt);
      }
    });
    getContentPane().add(jButton1, java.awt.BorderLayout.PAGE_END);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void onDrueckMich(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onDrueckMich
  {//GEN-HEADEREND:event_onDrueckMich
    // TODO add your handling code here: 
    
    //final String inhalt = tfText.getText();
    lbText.setText(String.format("Anzahl: %d", ++zaehler));
    
    pack();
    
  }//GEN-LAST:event_onDrueckMich

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(MeinErstesJavaSwingFenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(MeinErstesJavaSwingFenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(MeinErstesJavaSwingFenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(MeinErstesJavaSwingFenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new MeinErstesJavaSwingFenster().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel lbText;
  private javax.swing.JTextField tfText;
  // End of variables declaration//GEN-END:variables
}
